# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bmc < Formula
  desc "Bill McCloud's AWS toolbox — profile selection, EC2/ECS operations, console access"
  homepage "https://github.com/wearetechnative/bmc"
  version "0.5.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wearetechnative/bmc/releases/download/v0.5.2/bmc_0.5.2_darwin_amd64.tar.gz"
      sha256 "2be9c74437d07e7fba8e4f2d80b642b805198146d8fc59b7ea92eae394910f53"

      define_method(:install) do
        bin.install "bmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wearetechnative/bmc/releases/download/v0.5.2/bmc_0.5.2_darwin_arm64.tar.gz"
      sha256 "d995ba1e07de17fae44749d78d2aa4a036f8793e68e498702316e6ebc353f1b2"

      define_method(:install) do
        bin.install "bmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wearetechnative/bmc/releases/download/v0.5.2/bmc_0.5.2_linux_amd64.tar.gz"
      sha256 "50046997f27d94e4d26593728dfc1423c578a2ff26e2a7d3b36892c45e10d5a8"
      define_method(:install) do
        bin.install "bmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wearetechnative/bmc/releases/download/v0.5.2/bmc_0.5.2_linux_arm64.tar.gz"
      sha256 "2a73a2f6b0eb7bb4e90f2f4667c69711b5556a5679120cafe4a843e515a460af"
      define_method(:install) do
        bin.install "bmc"
      end
    end
  end

  test do
    system "#{bin}/bmc version"
  end
end
